## **Background**

Retention rate is one of the customer behaviors that can be necessary things in evaluating business performance. Retention rate shows the measurement of customer loyalty to consume our product in certain period. This project will analyze retention rate from one kind of retail store using cohort analysis.

Data Overview:
1. order_id : an unique code from every transaction.
2. product_code : an unique code from product
3. product_name : name of a product
4. quantity : number of goods ordered
5. order_date : datetime order created
6. price : price of a product
7. customer_id : an unique code from customer

In [3]:
import pandas as pd
import numpy as np 
import datetime as datetime
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
# Import dataset
file= 'https://drive.google.com/file/d/1ELg9NNsaC44Q8r-Y7i8UKzUwZuNKFEom/view?usp=sharing'
url= 'https://drive.google.com/uc?id=' + file.split('/')[-2]
datar= pd.read_csv(url)
datar.head()

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN

## **Exploratory Data Analysis**

In [10]:
data= datar.copy()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 461773 entries, 0 to 461772
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      461773 non-null  object
 1   product_code  461773 non-null  object
 2   product_name  459055 non-null  object
 3   quantity      461773 non-null  int64
 4   order_date    461773 non-null  object
 5   price         461773 non-null  float64
 6   customer_id   360853 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 24.7+ MB

In [ ]:
#

<class 'pandas.core.frame.DataFrame'>
Index: 360853 entries, 0 to 461744
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      360853 non-null  object
 1   product_code  360853 non-null  object
 2   product_name  360853 non-null  object
 3   quantity      360853 non-null  int64
 4   order_date    360853 non-null  object
 5   price         360853 non-null  float64
 6   customer_id   360853 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 22.0+ MB

## Coba

In [54]:
s= {'Tanggal':['2024-09-04','2024-03-07',202311],
    'Data':['A','B',None]}
afk= pd.DataFrame(s)
# afk['Tanggal']= pd.to_datetime(afk['Tanggal'], format='%Y%m')
afk['Tanggal']= afk['Tanggal'].astype('datetime64[ns]')
afk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Tanggal  3 non-null      datetime64[ns]
 1   Data     2 non-null      object
dtypes: datetime64[ns](1), object(1)
memory usage: 180.0+ bytes

In [55]:
afk

                        Tanggal  Data
0 2024-09-04 00:00:00.000000000     A
1 2024-03-07 00:00:00.000000000     B
2 1970-01-01 00:00:00.000202311  None

In [58]:
afk['Datetime']= afk['Tanggal'].dt.to_period('D')
afk

                        Tanggal  Data    Datetime
0 2024-09-04 00:00:00.000000000     A  2024-09-04
1 2024-03-07 00:00:00.000000000     B  2024-03-07
2 1970-01-01 00:00:00.000202311  None  1970-01-01

In [26]:
from operator import attrgetter
afk['distance']= (afk['Datetime']-afk['Datetime']).apply(attrgetter('n'))+1
afk

     Tanggal Data Datetime  distance
0 2024-01-01    A  2024-01         1
1 2023-12-01    B  2023-12         1

In [37]:
ok= (afk.loc[0,'Datetime']-afk.loc[0,'Datetime'])
print(dir(ok))

['__add__', '__array_priority__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__mul__', '__ne__', '__neg__', '__new__', '__pyx_vtable__', '__radd__', '__reduce__', '__reduce_cython__', '__reduce_ex__', '__repr__', '__rmul__', '__rsub__', '__setattr__', '__setstate__', '__setstate_cython__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '_adjust_dst', '_apply', '_apply_array', '_attributes', '_cache', '_day_opt', '_from_name', '_get_offset_day', '_offset_str', '_params', '_period_dtype_code', '_prefix', '_repr_attrs', '_use_relativedelta', '_validate_n', 'base', 'copy', 'freqstr', 'is_anchored', 'is_month_end', 'is_month_start', 'is_on_offset', 'is_quarter_end', 'is_quarter_start', 'is_year_end', 'is_year_start', 'kwds', 'n', 'name', 'nanos', 'normalize', 'rollback', 'rollforward', 'rule_code']

In [51]:
bl= afk.dropna(how='any')
vl= afk[~afk['Data'].isna()]
bl

     Tanggal Data
0 2024-01-01    A
1 2023-12-01    B